### ISSUE TITLE
Reduce resolution of save as PNG

### ISSUE THREAD

**Issue by homonecloco** [homonecloco/biojs-vis-expression-bar#17]
the “save as png” button does not work for me in neither firefox, chrome nor IE
UAUY: it works for me, but I only see 2 out of the 3 homoeologues in my file.. So I am seeing 3 homoeologues but then only 2 show in the png..

**Comment by homonecloco** [comment]
I need to know what gene with which filters people have issues with.

**Comment by NikolaiAdamski** [comment]
I tried it with:
Traes_2BS_2909928C4
Traes_2BS_40DF3E2C8

**Comment by homonecloco** [comment]
And the filters and displayed factors? I think how you filtered would have a bigger effect on the figure (as the size increases by the number of displayed bars).
