### ISSUE TITLE
Image with expression

### ISSUE THREAD

**Issue by homonecloco** [homonecloco/biojs-vis-expression-bar#19]
It would be really cool to have a picture of a wheat plant at different developmental stages, then you click on your favourite gene, and a heat map shows where it is expressed.
UAUY: not now.. we also do not have sufficient resolution to do this based on the available RNAseq samples we have.. so no..

**Comment by homonecloco** [comment]
I did think about it, when I saw this: 
http://biojs.io/d/biojs-xpression

**Comment by NikolaiAdamski** [comment]
I would agree with Cristobal: We don't have enough resolution for this. Plus, it is really just a gimmick.

**Comment by homonecloco** [comment]
Ah, yes, I also agree is a gimmick... Ben is gone, but I tried to convinced him at some point to make a a way to add your own generic figure.  I'm putting the issue just for the record.

**Comment by homonecloco** [comment]
This is
