### ISSUE TITLE
Ternary plot

### ISSUE THREAD

**Issue by homonecloco** [homonecloco/biojs-vis-expression-bar#33]
We need to implement a Ternary plot. There are two options: 

1. Integrate [d3-ternary](https://github.com/davenquinn/d3-ternary/)
2. Implement the code from  [here](http://bl.ocks.org/tomgp/7674234)

I would prefer ```2``` as we can have more control on how we change the colours dynamically, highlight dots, etc. 

There is going to be a check to display the ternary plot. The control is only visible when ```tern``` and ```tern_order``` are in the top level of the ```json``` file. It looks like this:

```json
"tern": {
        "A":"Traes_5AS_693F754D9.1",
        "B":"Traes_5BS_E71DA05B9.1",
        "D":"Traes_5DS_7FCEC252F.1"
    }, 
    "tern_order":["A","B","D"],
```
The keys on ```tern``` should be the names in the corner of the triangle, and the values will be displayed in the margins. 

The ```tern_order``` defines the order of the axes. Element 0 left axis, 1 right axis and 2 bottom axis. 

There is an example in the [repository](https://github.com/homonecloco/biojs-vis-expression-bar/blob/master/snippets/data/ternary_plot.json) of the data structure. 

The implementation of the plot should be in a new ``.js`` file, similar tho ```heatmap.js```.  All the methods for the ```Heatmap``` class must be implemented from scratch to render the ternary plot. The data will be in ```this.parent.data.renderedData```, which is generated from the general controls.  The idea is that the ternary plot will replace the the barchart. To change the plot, the ```this.renderObject``` needs to be swapped before calling ```refreshSVG()```. This should completely swap the control. A test for this idea could be to have a heat map thick on the barchart, and swap the methods for the heat map .

**Comment by Bijan-Ghasemi-Afshar** [comment]
**## Task: Initial_Structure**
* Put the ternary plot checkbox in the setup container and disabled by default
* If changed, change its state
* Store its value in session storage
* If the data has 3 tern keys, display the ternary plot checkbox

**Comment by Bijan-Ghasemi-Afshar** [comment]
# Expression Bias

1. Calculate all the percentage of contribution from "Expression-bias-value"
2. Calculate the centroid
3. Calculate the average distance between the centroid and each displayed value
4. Plot 2 lines with *Something I can't read

**Comment by homonecloco** [comment]
4. Plot 2 lines in the top with 10 divisions each.  Dived them in brackets of 0.1. For now, put a dot in the average distance to the centroid. I'll write more instructions later.

**Comment by homonecloco** [comment]
The base of the ternary plot is done. What is missing are bugs and new features
