### ISSUE TITLE
Expression Bias movment. 

### ISSUE THREAD

**Issue by homonecloco** [homonecloco/biojs-vis-expression-bar#38]
1. Calculate all the percentage of contribution from "Expression-bias-value" (need more info)
2. Calculate the centroid (need to know how to calculate)
3. Calculate the average distance between the centroid and each displayed value
4. Plot a vertical line that goes from 0 to 1, divided in brackets of 0.1
5. Highlight the bracket that has the value of the average distance of all the points to the centroid (for now)

This is what is the second part of #33

**Comment by homonecloco** [comment]
The title should be:

```expression_bias.keys[N]```  homoeolog expression bias 

coming from the json (in example like this)

```
"expression_bias":{
      "Azhurnaya":         [0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.90],
      "Chinese Spring": [0.10,0.15,0.20,0.40,0.45,0.50,0.70,0.90]
  },
```

So, it would have two bars (```Azhunraya homoeolog expression bias``` and ```Chinese Spring homoeolog expression bias```).

The Average distance between the centroid and all the values (calculated in 3) should map to the corresponding bracket. So, if the value is 0.16 it should go to the second bracket in Azhurnaya and the third bracket in Chinese Spring). 

Finally, on the left side add the label ```stable``` and on the right side ```dynamic```.

**Comment by Bijan-Ghasemi-Afshar** [comment]
Show the value of the expression bias when it is hovered over

**Comment by homonecloco** [comment]
the tooltip should show for Azhurnaya:

```
Average distance from centroid: 0.34
Homoeolog Expression bias decile: 4
Homoeolog  Expression bias range: (0.3, 0.4)
```

Note that the leftmost is in index 1 (not 0). 

Also, keep the centroid circle hidden, but show it on the top of the plot when you roll over the box.  

And for extra points, draw a line between the centroid and all the other points.

**Comment by homonecloco** [comment]
To add the colours, you need to add something like:

```
"expression_bias_colors" : {
       "Azhurnaya":        ["#377eb8", "#bdbdbd", "#bdbdbd","#bdbdbd","#bdbdbd","#bdbdbd","#bdbdbd","#bdbdbd","#bdbdbd", ""#e41a1c"],
      "Chinese Spring": ["#377eb8", "#bdbdbd", "#bdbdbd","#bdbdbd","#bdbdbd","#bdbdbd","#bdbdbd","#bdbdbd","#bdbdbd", ""#e41a1c"]
}
```

If the color for a dataset is missing, use a grey default ("#bdbdbd"). Validate that the array is not null.

**Comment by homonecloco** [comment]
If the ```expression_bias``` key is missing, the ternary plot now crashes. Add a validation to only render the expression bias when the hash is present.
