### ISSUE TITLE
Ternary plot scrollbar is hidden

### ISSUE THREAD

**Issue by homonecloco** [homonecloco/biojs-vis-expression-bar#40]
Make the scrollbar for the ternary plot visible by giving a maximum width.

The width is related to the height too. It needs to be validated in both axes. 

This is the actual bug in homonecloco/expvip-web#27

**Comment by Bijan-Ghasemi-Afshar** [comment]
The Scrollbar is not hidden anymore and the svg content fits inside the div that contains it
