### ISSUE TITLE
Add description of the selected value

### ISSUE THREAD

**Issue by homonecloco** [homonecloco/biojs-vis-expression-bar#8]
Describe TPM/count in a rollover  (On the bar, or on its selector?)

**Comment by NikolaiAdamski** [comment]
I would prefer it to be on the selector, i.e. when you choose between counts and tpm.

**Comment by homonecloco** [comment]
A description for tpm and count would be good. Is count FPKM? Some people might not know what tpm is.
RICARDO: As for your question, Count is the raw count of the reads. We haven’t included the FPKMs, as the TPM are the transcripts per million, which considers the total number of transcripts sequenced (as opposed to the total transcripts in the reference in the FPKM).  
UAUY: this will go into the documentation. However we could change the wording on the browser to say “Unit of expression” instead of “property”.  Likewise if this font size could be the same as the “Save as SVG”, etc then it would make it cleaner.. the same goes with the “Homoeologues” button which is currently too small compared to the “Save as…” fonts.

**Comment by homonecloco** [comment]
OLU: Is it possible to have the information (experiment, Sra number , paper e.t.c)  about each sample displayed when you hover over them with the mouse? I know this is available for the filter options but it will be more useful for the samples I.D next to the graph
UAUY: This goes to Brande’s comment as well. The problem of “clicking” is that when you do this in the boxes it sorts them… We could improve the nomenclature on the boxes and I can provide an updated list of this… I just need you to send me the list order so I can include this in more detail.. with respect to a link to the papers we can have this in the further documentation.. I am not sure how to link to the paper directly from the browser…

**Comment by homonecloco** [comment]
Fixed mostly in commit 31060ac18d6cae3e56e74b72147948f28b1636e3 . De description of the Expression values will be added in the web interface.
